Improved error handling (#49)
* Improved error handling

- include rudimentary error handling
  - use `set -e` and `set -eo pipefail` if appropriate
  - use && in other cases
- fix permission issue with zeebe backup jobs

* Further improvements to error handling

* Ran ShellCheck

- executed ShellCheck and corrected all findings:

diff --git a/03 - Lab 3 - Backup and Restore/backup/zeebe-backup-job.yaml b/03 - Lab 3 - Backup and Restore/backup/zeebe-backup-job.yaml
--- a/03 - Lab 3 - Backup and Restore/backup/zeebe-backup-job.yaml
+++ b/03 - Lab 3 - Backup and Restore/backup/zeebe-backup-job.yaml
@@ -18,8 +18,11 @@ spec:
         args:
         - -c
         - |
+          #!/bin/bash
+          set -e
+
           # Trigger the backup
-          curl -X POST "http://camunda-zeebe-gateway:9600/actuator/backups" \
+          curl --fail -X POST "http://camunda-zeebe-gateway:9600/actuator/backups" \
             -H 'Content-Type: application/json' \
             -d "{\"backupId\": \"$BACKUP_TIME_ID\"}"
           echo "Backup trigger request sent for ID $BACKUP_TIME_ID"
@@ -28,7 +31,7 @@ spec:
           # Monitor backup status
           fail_count=0
           while true; do
-            response=$(curl -s "http://camunda-zeebe-gateway:9600/actuator/backups/$BACKUP_TIME_ID")
+            response=$(curl --fail -s "http://camunda-zeebe-gateway:9600/actuator/backups/$BACKUP_TIME_ID")
             echo "$response"
             
             # Check if the response includes the specific backupId and state COMPLETED
@@ -42,7 +45,7 @@ spec:
               echo "Backup $BACKUP_TIME_ID failed or in an unknown state."
               fail_count=$((fail_count+1))
               if [ $fail_count -ge 3 ]; then
-                echo "Failed 3 times, exiting."
+                echo "ERROR: Failed 3 times, exiting." >&2
                 exit 1
               else
                 echo "Retrying, attempt $fail_count of 3."
diff --git a/03 - Lab 3 - Backup and Restore/backup/zeebe-export-pause.yaml b/03 - Lab 3 - Backup and Restore/backup/zeebe-export-pause.yaml
--- a/03 - Lab 3 - Backup and Restore/backup/zeebe-export-pause.yaml
+++ b/03 - Lab 3 - Backup and Restore/backup/zeebe-export-pause.yaml
@@ -12,8 +12,15 @@ spec:
         args:
         - -c
         - |
-          curl -X POST "http://camunda-zeebe-gateway:9600/actuator/exporting/pause?soft=true" \
+          #!/bin/bash
+          curl --fail -X POST "http://camunda-zeebe-gateway:9600/actuator/exporting/pause?soft=true" \
             -H 'Content-Type: application/json' \
             -d '{}'
-          echo "Exporting paused on camunda-zeebe-gateway."
+          success=$?
+          if [ "$success" ]; then
+            echo "Exporting paused on camunda-zeebe-gateway."
+          else
+            echo "ERROR: Could not pause exporting on camunda-zeebe-gateway"  >&2
+            exit 1
+          fi
       restartPolicy: Never
diff --git a/03 - Lab 3 - Backup and Restore/restore/es-snapshot-restore-job.yaml b/03 - Lab 3 - Backup and Restore/restore/es-snapshot-restore-job.yaml
--- a/03 - Lab 3 - Backup and Restore/restore/es-snapshot-restore-job.yaml
+++ b/03 - Lab 3 - Backup and Restore/restore/es-snapshot-restore-job.yaml
@@ -19,7 +19,8 @@ spec:
         - -c
         - |
           #!/bin/sh
-          
+          set -eo pipefail
+
           # Define Elasticsearch endpoint
           elasticsearch_endpoint="http://camunda-elasticsearch:9200"
           
@@ -31,7 +32,7 @@ spec:
             echo "Processing repository: $repository"
             
             # Query Elasticsearch for all snapshots in the repository
-            response=$(curl -s "$elasticsearch_endpoint/_snapshot/$repository/_all")
+            response=$(curl --fail -s "$elasticsearch_endpoint/_snapshot/$repository/_all")
 
             # Attempt to extract snapshot names that include the BACKUP_TIME_ID. This uses a simplistic method with grep and cut.
             # Note: This method relies on the snapshot names being in a specific format in the response.
@@ -40,10 +41,11 @@ spec:
                 echo "Found snapshot matching criteria: $snapshot in $repository"
                 # Restore the found snapshot
                 echo "Restoring snapshot: $snapshot in repository: $repository"
-                curl --request POST "$elasticsearch_endpoint/_snapshot/$repository/$snapshot/_restore?wait_for_completion=true"
+                curl --fail --request POST "$elasticsearch_endpoint/_snapshot/$repository/$snapshot/_restore?wait_for_completion=true"
                 echo "Restore completed for snapshot: $snapshot in repository: $repository"
               else
-                echo "No matching snapshots found in repository $repository."
+                echo "ERROR: No matching snapshots found in repository $repository." >&2
+                exit 1
               fi
             done
           done
diff --git a/03 - Lab 3 - Backup and Restore/restore/zeebe-restore-job-1.yaml b/03 - Lab 3 - Backup and Restore/restore/zeebe-restore-job-1.yaml
--- a/03 - Lab 3 - Backup and Restore/restore/zeebe-restore-job-1.yaml
+++ b/03 - Lab 3 - Backup and Restore/restore/zeebe-restore-job-1.yaml
@@ -11,12 +11,16 @@ spec:
         command: ["/bin/bash", "-c"]
         args:
         - |
-          ls -laR /usr/local/zeebe/data;
-          rm -rf /usr/local/zeebe/data/* /usr/local/zeebe/data/.*;
+          #!/bin/bash
+          ls -lAR /usr/local/zeebe/data
+          rm -rf /usr/local/zeebe/data/{*,.*}
           echo "Starting restoration process..."
-          ls -laR /usr/local/zeebe/data;
-          /usr/local/zeebe/bin/restore --backupId=${ZEEBE_RESTORE_FROM_BACKUP_ID}
-          echo "Restoration complete."
+          if [ -z "$(ls -A /usr/local/zeebe/data)" ]; then
+            /usr/local/zeebe/bin/restore --backupId="${ZEEBE_RESTORE_FROM_BACKUP_ID}" && echo "Restoration complete."
+          else
+            echo "ERROR: Could not delete zeebe data" >&2
+            exit 1
+          fi
         env:
         - name: ZEEBE_RESTORE_FROM_BACKUP_ID
           valueFrom:
@@ -48,9 +52,6 @@ spec:
         volumeMounts:
         - name: data
           mountPath: /usr/local/zeebe/data
-        securityContext:
-          runAsUser: 1000
-          runAsNonRoot: true
       securityContext:
         fsGroup: 1000 
       volumes:
